- client/cmd/key_utils.go
- go.mod
- go.sum
fixes secp256k1 key uncompression bug in the validator CLI
issue: fixes #50
> fix(client/validator): use correct secp256k1 key uncompression

- lib/buildinfo/buildinfo.go
bumps the story client to 0.9.11 stable
issue: none
> chore(release): bump client to 0.9.11 stable

- lib/buildinfo/buildinfo.go
begins the new `story` client 0.9.12 unstable release cycle
issue: none
> chore(release): begin 0.9.12 unstable release

- client/x/evmstaking/types/withdraw_test.go
This PR increased test coverage of [client/x/evmstaking/types/withdraw.go](https://github.com/piplabs/story/blob/main/client/x/evmstaking/types/withdraw.go) from 0% to 100%.
issue: #64
> test(evmstaking/types): add test cases for withdraw

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/withdrawal_queue_test.go
Increased test coverage of [client/x/evmstaking/keeper/withdrawal_queue.go](https://github.com/piplabs/story/blob/main/client/x/evmstaking/keeper/withdrawal_queue.go) from 0% to 78.8%
- All application logic written on the Story side, excluding the SDK.
- **What’s Not Covered (Edge Cases Related to the SDK)**
- Failed to get paramstore: this could occur if the param store is broken or not initialized properly.
- Failures related to collections: this includes potential failures during KV store iteration.
**changes:**
- `s.addrs`: create accounts should be called after setting bech32 prefix correctly, unless it has cosmos prefix.
- `accountKeeper.EXPECT().GetModuleAddress`
- it is more natural for returning fixed module addresses instead of randomly created account's …
> test(evmstaking/keeper): add test cases for withdrawal queue

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/withdraw.go
- client/x/evmstaking/keeper/withdraw_test.go
**coverage:**
- Increased test coverage from 0% to 86.8%
- **What’s Not Covered (Edge Cases Related to the SDK)**
- Failed to get validators (storage might broken)
- Failed to get value from sdk store (e.g. `NextValidatorSweepIndex`)
- etc...
**changes:**
- fixed error message
- added `accountKeeper`, `distributionKeeper` as test suite fields for writing new test codes using those keepers.
issue: #64
> test(evmstaking/keeper): add test cases for withdraw

- client/x/evmstaking/keeper/validator_test.go
**coverage:**
- Increased test coverage from 0% to 86.0%
- What's Covered
- What’s Not Covered (Edge Cases Related to the SDK)
- Failed to set collections map
- Failed to get validator, but the reason is not `ErrNoValidatorFound`
- Failed to create `MsgCreateValidator`
- ...
**changes:**
- added `accountKeeper` as a field of TestSuite for writing new test codes using `accountKeeper`.
issue: #64
> test(evmstaking/keeper): add test cases for validator

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/set_address_test.go
Increased test coverage from 0% to 87.5%
- **What’s Not Covered (Edge Cases Related to the SDK)**
- Failed to set of map (= collections)
issue: #64
> test(evmstaking/keeper): add test cases for set address

- client/x/evmstaking/keeper/deposit.go
- client/x/evmstaking/keeper/deposit_test.go
- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/withdraw_test.go
**coverage:**
- Increased test coverage from 0% to 94.4%
- **What’s Not Covered (Edge Cases Related to the SDK)** 
- Failed to set of map (= collections)
- Staking keeper type assertion 
**changess**
- Added account keeper as a field of test suite (we need this for writing testing code)
- fix error message
issue: #64
> test(evmstaking/keeper): add test cases for deposit

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/msg_server_test.go
- client/x/evmstaking/keeper/withdraw_test.go
Increase test coverage of https://github.com/piplabs/story/blob/main/client/x/evmstaking/keeper/msg_server.go from 0% to 95.5%.
issue: close #64
> test(evmstaking/keeper): add test cases for msg server

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/staking_queue_test.go
Increased test coverage from 0% to 84.6%
- **What’s Not Covered (Edge Cases Related to the SDK)**
- failed to get iterator
- failed to unmarshal
issue: #64
> test(evmstaking/keeper): add test cases for staking queue

- client/x/evmstaking/keeper/keeper_test.go
increased coverage from 11.4% to 94.3%
covered:
- almost every code paths of `ProcessStakingEvents`
- previous not-covered methods (= `Logger`, `Keeper.GetAuthority`, `Keeper.ValidatorAddressCodec`)
not covered:
- panic cases during NewKeeper (e.g. binding contracts fails, address codec broken, etc...) 
changes:
- move common test helper function `createCorruptedPubKey` to from `withdraw_test` to `keeper_test`
issue: #64
> test(evmstaking/keeper): add test cases for keeper

- client/x/evmengine/types/upgrade_contract_test.go
increased coverage to 100%
note: disabled lint check for package name to test private methods
issue: #81
> test(evmengine/types): add test cases for upgrade contract

- client/x/evmengine/keeper/upgrades_internal_test.go
increased test coverage to 100%.
**notes**
I followed the existing test conventions for the evmengine module:
- Tests are written in the form of `{file}_internal_test.go` within the same package.
- Each test is implemented as an individual Test function.
In my opinion, it would be better for future maintainability to manage the tests with `TestSuite`, similar to the `evmstaking` module. However, changing all the existing test code to this format would require a significant amount of work, so I have adhered to the current convention for now.
If you guys have any different thoughts on this, please feel free to let me know.
issue: #81
> test(evmengine/keeper): add test cases for upgrades

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/msg_server_test.go
- client/x/evmstaking/keeper/redelegation_test.go
- client/x/evmstaking/keeper/staking_queue_test.go
- client/x/evmstaking/keeper/withdraw_test.go
increased coverage from 72.4% to 100%
**changes**
- added test cases for existing redelegation test code
- updated and moved common test helper function `setupValidatorAndDelegation` to `keeper_test.go`
issue: #64
> test(evmstaking/keeper): add test cases for redelegation

- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/params_test.go
increased test coverage to 70%
**not covered**
- marshaling error
- sdk store error
- old validator sweep existing case
issue: #64
> test(evmstaking/keeper): add test cases for params

- lib/buildinfo/buildinfo.go
starts the new v0.10.1 unstable release cycle
issue: none
> chore(release): begin story v0.10.1 unstable release

- client/x/evmstaking/types/params.go
- client/x/evmstaking/types/params_test.go
- client/x/evmstaking/types/withdraw_test.go
increased test coverage to 100% 
**changes**
- Updated the input types of validation functions to use concrete types instead of any, as there doesn’t appear to be a specific reason for using any. (Please let me know if there’s a reason for it)
- Renamed the withdrawal test suite to avoid naming conflicts with the parameter test suite.
issue: #64
> test(evmstaking/types): add test cases for params

- client/x/evmstaking/keeper/genesis_test.go
increased coverage to 71.4%
**not covered**
- sdk related errors
- failed to set values to the store
- failed to initialize withdraw queue
- corrupted value was in staking module's state 
- failed to get values from store
issue: #64
> test(evmstaking): add test cases for genesis

- client/x/evmstaking/keeper/grpc_query.go
- client/x/evmstaking/keeper/grpc_query_test.go
- client/x/evmstaking/keeper/keeper_test.go
append `QueueElementsPrefixSuffix` when query elements of withdrawal queue. without appending `QueueElementsPrefixSuffix`, query fails.
issue: fixes #84
> fix(evmstaking): query withdrawal queue

- client/x/evmengine/keeper/helpers_internal_test.go
increased test coverage to 100%
issue: #81
> test(evmengine): add test cases for helper

- .golangci.yml
- client/x/evmengine/keeper/keeper_internal_test.go
- lib/ethclient/enginemock.go
increased test coverage to 89.7%
issue: #81
> test(evmengine): add test cases for keeper

- client/x/evmengine/keeper/db_internal_test.go
- client/x/evmengine/keeper/genesis_internal_test.go
- client/x/evmengine/keeper/keeper_internal_test.go
increase coverage to 83.3%
not covered part is sdk's store related errors (e.g. failed to get params from store)
issue: #81
> test(evmengine): add test cases for genesis

- client/x/evmengine/keeper/params_internal_test.go
increased coverage to 77.3%
not covered part is sdk's store related errors (e.g. failed to get params from store)
issue: #81
> test(evmengine): add test cases for params

- client/x/evmengine/keeper/keeper.go
cmtAPI is lazily set, so during replaying blocks it is nil.
we should add nil checking logic to avoid panic. 
this PR is non state breaking meaning code changes won't do any state changes. so the PR doesn't require hard fork.
issue: #127
> fix(evmengine): nil panic with optimistic build enabled

- client/x/evmengine/keeper/abci_internal_test.go
- client/x/evmengine/keeper/keeper_internal_test.go
- client/x/evmengine/keeper/msg_server_internal_test.go
- client/x/evmengine/keeper/proposal_server_internal_test.go
- client/x/evmengine/keeper/upgrades_internal_test.go
- client/x/evmstaking/keeper/keeper_test.go
- lib/ethclient/enginemock.go
increased coverage of `evmengine/keeper/msg_server.go` to 86.8% without considering un-used code `compareWithdrawals`.
**`mockEngineAPI`**
- `forceInvalidNewPayloadV3` and `forceInvalidForkchoiceUpdatedV3` are added to simulate failed engine apis with invalid status return.
**`engineMock`**
- `storeKey` is added to make engineMock dependent on `sdk.Context` for better testability.
- By using `storeKey`, engineMock's methods can interact with the `sdk.Context`'s store, allowing for independent tests that do not interfere with each other’s store state. 
- now we can use cacheContext to test engineMock
**`NewBlock`**
- Because of above changes, we need to rlp encode and decode block data. But if we create a block with nil withdrawals and nil withdrawalHash, rlp doesn't work well (couldn't …
> test(evmengine/keeper): add test cases for msg server

- client/x/evmstaking/keeper/abci.go
- client/x/evmstaking/keeper/abci_test.go
modifies the branch check in the evmstaking module's unbonded stakes logic
issue: none
> fix(x/evmstaking): endblock unbond branch check

- client/genutil/defaults.go
- client/genutil/genutil_internal_test.go
- lib/netconf/iliad/genesis.json
- lib/netconf/local/genesis.json
- lib/tutil/testdata/genesis.json
Disable VoteExtension by default for all network. We can enable this for future by setting `vote_extensions_enable_height`.
issue: #172
> feat(genesis): disable vote extension by default

- client/cmd/cmd.go
- client/cmd/flags.go
- client/cmd/key_utils.go
- client/cmd/keys.go
- client/cmd/validator.go
Adds the `story key convert` subcommand for allowing users to convert between different key types. Users may run one of the following commands to view the EVM, validator, and delegator account formats associated with their derived pub key:
- `story key convert --private-key-file ${EVM_PRIVATE_KEY_ENV_FILE}`
- `story key convert --validator-key-file ${PATH_TO_YOUR_VALIDATOR_KEY}`
- `story key convert --pubkey-hex ${COMPRESSED_PUBKEY_IN_HEX}`
- `story key convert --pubkey-base64 ${COMPRESSED_PUBKEY_IN_BASE64}`
- `story key convert --pubkey-hex-uncompressed ${UNCOMPRESSED_PUBKEY_IN_HEX}`
issue: fixes #155
> feat(cli): add key conversion subcommand

- client/x/evmstaking/keeper/abci.go
- client/x/evmstaking/types/expected_keepers.go
- go.mod
- go.sum
With [this implementation](https://github.com/piplabs/cosmos-sdk/pull/4), I replaced the EndBlocker of staking keeper. 
It now returns the array of completed unbonding, so we can use them for processing withdrawal.
issue: #197
> feat(evmstaking): replace staking keeper endblocker

- contracts/script/GenerateAlloc.s.sol
- contracts/script/TestPrecompileUpgrades.s.sol
- contracts/src/interfaces/IIPTokenStaking.sol
- contracts/src/interfaces/IUpgradeEntrypoint.sol
- contracts/src/protocol/IPTokenStaking.sol
- contracts/src/protocol/UpgradeEntrypoint.sol
- contracts/test/deploy/Create3.t.sol
- contracts/test/libraries/Secp256k1.t.sol
- contracts/test/script/DeployCore.t.sol
- contracts/test/stake/IPTokenStaking.t.sol
- contracts/test/upgrade/UpgradeEntryPoint.t.sol
- contracts/test/utils/Test.sol
Smart Contracts must have GPL-3.0-only, not BUSL, since we forked from Omni.
issue: none
> fix(contracts): fix licenses from busl to gpl

- contracts/src/interfaces/IIPTokenStaking.sol
- contracts/src/protocol/IPTokenStaking.sol
- contracts/test/stake/IPTokenStaking.t.sol
Adds redelegateOnBehalf method for operators to redelegate on behalf or delegators
issue: none
> feat(staking): redelegate on behalf

- contracts/script/GenerateAlloc.s.sol
- contracts/src/interfaces/IIPTokenStaking.sol
- contracts/src/libraries/Errors.sol
- contracts/src/protocol/IPTokenStaking.sol
- contracts/test/stake/IPTokenStaking.t.sol
Removes period durations from smart contract so it's not duplicated in EL ad CL.
issue: none
> fix(staking): removing period values from staking contract

- lib/netconf/local/genesis.json
This is an update according to https://github.com/piplabs/story-geth/pull/43.
This includes predeployment of UBIPool contract
issue: none
> chore(genesis): update execution block hash

- client/cmd/flags.go
- client/cmd/init.go
allows overriding the persistent peers setting on initialization
issue: none
> feat(cmd): add persistent peers init override

- contracts/src/interfaces/IIPTokenStaking.sol
- contracts/src/protocol/IPTokenStaking.sol
- contracts/test/stake/IPTokenStaking.t.sol
Redelegate was mistakenly payable. Tokens are already in CL.
issue: fixes https://github.com/piplabs/story/issues/255
> fix(staking): fix redelegate

- client/x/evmstaking/types/params.go
- client/x/mint/keeper/abci.go
- go.mod
- go.sum
- lib/netconf/local/genesis.json
- lib/netconf/odyssey/genesis.json
With disabling the slash within singularity (https://github.com/piplabs/cosmos-sdk/pull/17), I added genesis param to our genesis.json file. The version of cosmos-sdk for replacement should be updated after merging the PR and release. 
issue: none
> feat(genesis): add singularity height to slashing module

- client/app/app.go
- client/app/app_config.go
- client/app/keepers/types.go
- go.mod
- go.sum
With [this](https://github.com/piplabs/cosmos-sdk/pull/18), slashing for double signing is also disabled during singularity.
issue: none
> feat(evidence): add evidence module with singularity

- lib/netconf/odyssey/genesis.json
Changed singularity height for odyssey to 40 days with assuming 3s of block time.
issue: none
> chore(genesis): change singularity height for odyssey testnet

- client/x/evmstaking/keeper/withdraw.go
When a delegator delegates token multiple times, the accumulated reward token is transferred to the cosmos account. 
In this case, we need to cover this as well in reward withdrawal.
issue: none
> feat(evmstaking): handle claimed reward in account

- client/x/evmengine/keeper/ubi.go
- client/x/evmengine/keeper/upgrades.go
- client/x/evmengine/types/events.go
- client/x/evmstaking/keeper/delegator_address.go
- client/x/evmstaking/keeper/deposit.go
- client/x/evmstaking/keeper/redelegation.go
- client/x/evmstaking/keeper/unjail.go
- client/x/evmstaking/keeper/update_commission.go
- client/x/evmstaking/keeper/validator.go
- client/x/evmstaking/keeper/withdraw.go
- go.mod
- go.sum
- lib/errors/codes.go
- lib/netconf/local/genesis.json
- lib/netconf/odyssey/genesis.json
add more failure event logs
issue: none
> feat(staking): add more failure event logs

- contracts/foundry.toml
- contracts/package.json
- contracts/pnpm-lock.yaml
- contracts/script/GenerateAlloc.s.sol
- contracts/src/libraries/Predeploys.sol
- contracts/src/token/WIP.sol
- contracts/test/token/WIP.t.sol
- contracts/test/utils/Test.sol
Introduce Wrapped IP and predeploy WIP in genesis
issue: none
> feat(wip): introduce wrapped ip and predeploy

- .github/workflows/build-release-artifacts.yml
- client/cmd/flags.go
adds moniker as an init flag to override default node naming
issue: none
> chore(cmd/flags): add moniker as init flag

- .github/workflows/build-release-artifacts.yml
pins go version to 1.22.0 for the release workflow
issue: none
> chore(workflows): pin release workflow version to 1.22.0

- client/x/evmengine/keeper/evmmsgs.go
- client/x/evmengine/keeper/helpers.go
remove sorting (use filtered logs indice as-is) and add retry with timeout for evm events
issue: #301
> fix(x/evmengine): remove sort & retry with timeout for events

- client/x/evmstaking/keeper/deposit.go
- client/x/evmstaking/keeper/validator.go
The issue was due to that our evmstaking module don't handle errors while processing evm events.
When errors occur while processing `CreateValidator` or `Stake` evm events, the minted tokens should be sent back to module and burnt.
issue: #262
> fix(evmstaking): roll back tokens to be burnt when msg failed

- .github/workflows/build-release-artifacts.yml
fixes a bug to upload the binary and its checksum to GH release page
issue: none
> chore(workflows): fix the action to upload artifacts

- go.mod
- go.sum
The previously imported package of `cosmossdk.io/evidence` was from cosmos/cosmos-sdk, not piplabs/cosmos-sdk.
So made a new release for evidence module modified by us and imported it correctly. 
([piplabs/x/evidence/v0.1.1-piplabs-v0.1](https://github.com/piplabs/cosmos-sdk/releases/tag/x%2Fevidence%2Fv0.1.1-piplabs-v0.1), following the naming rule for piplabs/cosmos-sdk)
This should prevent validator to be jailed and tombstoned due to double signing.
issue: #336
> chore(evidence): import piplabs evidence package

- go.mod
- go.sum
As described in #336, validator is jailed right after the singularity. It was due to that the skipping logic for downtime slashing was placed incorrectly. Fixed in [this PR](https://github.com/piplabs/cosmos-sdk/pull/25) and bump up the cosmos-sdk version accordingly.
issue: #336
> chore(*): bump cosmos ver for singularity slashing

- client/cmd/validator.go
Added a `data` arg to unjail command.
issue: #364
> fix(cli): add data arg to unjail command

- client/cmd/flags.go
- client/cmd/validator.go
Fix unstake command
- converting delegator's compressed pubkey to uncompressed pubkey
- changing name of flag for unstake amount
issue: #351
> fix(cli): add converting delegator pubkey from cmp to uncmp

- client/x/evmengine/keeper/abci.go
This PR is the commit from Omni to handle errors in PostFinalize gracefully (https://github.com/omni-network/omni/pull/2508). When non-deterministic response received from CometBFT, skip optimistic build.
issue: none
> fix(evmengine): graceful post finalize errors

- .secrets.baseline
- client/app/prouter.go
- client/x/evmengine/keeper/abci.go
- client/x/evmengine/keeper/abci_internal_test.go
- client/x/evmengine/keeper/msg_server.go
- client/x/evmengine/keeper/proposal_server.go
- lib/ethclient/client_test.go
- lib/ethclient/engineclient.go
- lib/ethclient/enginemock.go
This PR is the commit from Omni to handle errors of engineAPI (https://github.com/omni-network/omni/pull/2469).
issue: none
> fix(evmengine): handle engine errors

- go.mod
- go.sum
There was an failure in building binary due to conflicts of btcec version.
This PR is to resolve the issue by bumping up geth version to v1.14.8, which uses the same version of btcec.
related PR on geth: https://github.com/ethereum/go-ethereum/pull/30181
issue: none
> chore(package): bump up go-ethereum to v1.14.8

- client/app/rollback.go
- client/cmd/cmd.go
- client/cmd/flags.go
- client/cmd/rollback.go
- client/config/config.go
- client/config/rollback.go
rollback multiple Cosmos App blocks and corresponding CometBFT states
issue: none
> feat(app): rollback many blocks

- .golangci.yml
- client/app/start.go
- client/comet/comet.go
- client/x/evmengine/keeper/abci.go
- client/x/evmengine/keeper/abci_internal_test.go
- client/x/evmengine/keeper/keeper.go
- client/x/evmengine/keeper/keeper_internal_test.go
- client/x/evmengine/keeper/msg_server_internal_test.go
- client/x/evmengine/keeper/upgrades_internal_test.go
- client/x/mint/keeper/genesis_test.go
- client/x/mint/keeper/grpc_query_test.go
- client/x/mint/keeper/keeper_test.go
- lib/expbackoff/expbackoff_test.go
use comet's exposed validators functions to check if the local node is the next (predicted) proposer
issue: closes #388
> fix(evmengine): get next proposer via comet algo

- contracts/src/interfaces/IIPTokenStaking.sol
- contracts/src/protocol/IPTokenStaking.sol
- contracts/test/stake/IPTokenStaking.t.sol
To avoid possible frontrunning validator creation, we are removing this method as recommended by auditors.
issue: none
> fix(contracts): remove create validator on behalf

- client/cmd/comettoml.go
with `html/template`, the character " was escaped so that converted to &#34. Changed to `text/template` as done in [cometbft](https://github.com/cometbft/cometbft/blob/main/config/toml.go#L7).
issue: none
> chore(comet): change template package to avoid escape

- contracts/src/protocol/IPTokenStaking.sol
- contracts/test/stake/IPTokenStaking.t.sol
- TRST-R-5: Apply rounding mechanism to IPTokenStaking._unstake()
- TRST-R-3: IPTokenStaking stake() and stakeOnBehalf() do not check validator key to be valid
issue: none
> fix(contracts): more audit issues

- client/cmd/flags.go
- client/cmd/init.go
- client/config/config.go
- contracts/script/GenerateAlloc.s.sol
- lib/evmchain/evmchain.go
- lib/netconf/mainnet/genesis.json
- lib/netconf/network.go
- lib/netconf/static.go
Support mainnet with `--network` flag. The genesis.json and seeds.txt from Odyssey are used for now. We need to update this later. 
fyi, ref pr: #178 (which supports Odyssey)
issue: none
> feat(*): support mainnet with network flag

- client/cmd/validator.go
Fix create validator command to use `createValidator` instead of `createValidatorOnBehalf`.
issue: #429
> fix(cmd): change to use create validator

- client/cmd/flags.go
- client/cmd/validator.go
According to the changes of #358, rename the command for set/unset operator.
issue: none
> chore(cmd): rename operator command

- contracts/src/deploy/Create3.sol
- contracts/test/deploy/Create3.t.sol
Enhance pre-deployed CREATE3 to support deploying contracts to deterministic addresses calculated solely based on the salt, independent of the deployer address.
issue: none
> feat(create3): allow deployed solely based on salt

- lib/netconf/story/genesis.json
- lib/netconf/story/seeds.txt
update configs for testing
issue: none
> chore(*): update config files

- client/server/bank.go
- client/server/payload.go
add spendable balance API
issue: none
> feat(api): add spendable balance api

- client/server/README.md
- client/server/api.swagger.yaml
- client/server/bank.go
- client/server/distribution.go
- client/server/payload.go
- client/x/evmstaking/keeper/deposit.go
- client/x/evmstaking/keeper/redelegation.go
- client/x/evmstaking/keeper/unjail.go
- client/x/evmstaking/keeper/update_commission.go
- client/x/evmstaking/keeper/validator.go
- client/x/evmstaking/keeper/withdraw.go
- contracts/script/GenerateAlloc.s.sol
- lib/errors/codes.go
remove useless api and enhance event processing error codes
issue: none
> chore(staking): api and error codes

- client/app/upgrades/singularity/virgil/constants.go
- client/app/upgrades/singularity/virgil/upgrades.go
Add to change reward multiplier of period delegation for Mainnet. 
For Aeneid, the Virgil upgrade has already executed, so this change of upgrade handler do not change the multipliers for Aeneid. That means, anyone can sync blocks from the genesis with the new binary. 
This will only change the multipliers for Mainnet (`chainID` = `story-1`). This assumes that no period delegations will happen until the upgrade height since it will be in the singularity. 
Tested with localnet for the 2 cases
- mocking Aeneid (already upgrade executed, and sync block from the genesis with this new binary)
- mocking Mainnet (change staking params including rewards multiplier)
issue: none
> feat(upgrade): change rewards multiplier for mainnet

- Dockerfile
When building docker image, 2 warnings are shown:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match
- UndefinedVar: Usage of undefined variable '$NETWORK'
Fix those 2 warnings and enable to build docker image appropriately.
issue: none
> build(*): declare network var in dockerfile

- client/cmd/flags.go
- client/cmd/validator.go
Added some verifications to CLI to prevent potential fund loss.
- create validate: check if the validator does not exist
- stake, unstake, redelegate, unjail, and update commission rate (including onBehalf): check if the validator exist
- update commission rate: check if the new commission rate is valid based on the previous one
issue: none
> feat(cli): add verifications to cli

- contracts/script/upgrades/DeployNewIPTokenStaking_V1_0_1.s.sol
- contracts/src/interfaces/IIPTokenStaking.sol
- contracts/src/protocol/IPTokenStaking.sol
- contracts/test/stake/IPTokenStaking.t.sol
Instead of reverting, round down
issue: none
> feat(staking): relax unstake requirements by rounding down to gwei

- .secrets.baseline
- client/app/privkey.go
- client/app/privkey_test.go
- client/app/prompt.go
- client/cmd/flags.go
- client/cmd/init.go
- client/cmd/keys.go
- client/cmd/validator.go
- client/config/config.go
- go.mod
- go.sum
- lib/cmd/flags.go
Support validator priv key encryption. 
Operators can encrypt the newly generated private key with `--encrypt-priv-key` flag. Without this flag, no encryption is done for private key as before. The encrypted file is stored under `story/config/enc_priv_key.json`. 
For all validator CLI, the private key is retrieved from the encrypted private key file by decrypting it if the `enc_priv_key.json` file exists. Otherwise, it is retrieved from `.env` file.
To support the existing operators (using not encrypted key), one command is also added to encrypt the existing private key in `.env` file: `./story key encrypt`. It will generate the encrypted private key file under `story/config/enc_priv_key.json`. 
Also, introduced a new command to decrypt and show the encrypted key: `./story key …
> feat(cli): add to encrypt priv key

- client/x/evmengine/keeper/abci.go
- client/x/evmengine/keeper/keeper.go
- client/x/evmengine/keeper/msg_server.go
- client/x/evmengine/keeper/proposal_server.go
Previously, when the execution engine was syncing, it would keep retrying until evm syncing is done. However, evm syncing is stuck while downloading chain data because the requested head falls behind by more than 128 blocks, making it impossible to retrieve the missing data from other peers.
To support snap sync, `newPayloadV3` and `forkChoiceUpdatedV3` requests are now made with the latest head while the execution engine is syncing. During syncing, `prepareProposal`, `processProposal`, and `postFinalize` are skipped.
issue: #505
> feat(x/evmengine): support exec engine snap sync

- .secrets.baseline
- client/app/prompt.go
- client/cmd/flags.go
- client/cmd/keys.go
- client/cmd/validator.go
In the `CreateValidator` CLI, the public key is retrieved from `config.PrivateKey` instead of the validator key file (`priv_validator_key.json`).
Additionally, the encrypted key file path can now be passed as a flag, allowing operators to use the `*OnBehalf` CLI with key encryption.
issue: none
> fix(cli): retrieve pub key from priv key in create validator

- lib/netconf/local/genesis.json
Updated the execution hash for local devnet according to [this change](https://github.com/piplabs/story-geth/pull/117).
issue: none
> chore(genesis): update exec hash for local devnet

- .secrets.baseline
- client/cmd/cmd.go
- client/cmd/flags.go
Added alias for `--with-comet` flag, `--with-tendermint`, per request from KYVE team. This alias flag is also commonly used in cosmos ecosystem. 
issue: #517
> feat(cli): add alias of with comet flag

- client/cmd/cmd.go
It conflicts `PersistentPreRunE` of root cmd, so changed to use `PreRun` for run command.
issue: none
> fix(cli): change to use pre run for aliasing

- client/config/config.go
Set the default value of `--with-comet` flag for Aeneid and Mainnet.
issue: none
> chore(config): set default with comet true

- client/app/prouter.go
- client/app/upgrades.go
- client/app/upgrades/v_1_2_0/constants.go
- client/app/upgrades/v_1_2_0/upgrades.go
- client/x/evmengine/keeper/abci.go
- go.mod
- go.sum
These PR includes 3 commits for release v1.2.0 as below.
- disallow unexported fields in cosmos tx in processing proposal
- add check if the size of tx from EL exceeds the MaxTxBytes of abci request
- change max bytes of CL block to 20MB in consensus params
**v1.2.0 will require hardfork since it contains update of consensus params.**
issue: none
> feat(app): release v1.2.0

- client/x/evmengine/keeper/abci.go
- client/x/evmengine/keeper/abci_internal_test.go
- client/x/evmengine/keeper/keeper_internal_test.go
- client/x/evmengine/keeper/msg_server.go
- client/x/evmengine/keeper/msg_server_internal_test.go
- client/x/evmengine/keeper/proposal_server.go
- client/x/evmengine/keeper/proposal_server_internal_test.go
- client/x/evmengine/keeper/ubi.go
- client/x/evmengine/keeper/ubi_internal_test.go
- client/x/evmengine/keeper/upgrades_internal_test.go
- client/x/evmengine/types/executable_data.go
Added unit tests for evmengine module. The coverage of functions in keeper is increased from 64.9% to 84%.
issue: none
> test(x/evmengine): add unit tests for evmengine module

- .github/workflows/gotest.yml
Currently, no codecov report is generated when PR is merged into main, so no report is shown in codecov badge in README.md. So, enabled to generate report when a PR is merged into main.
issue: none
> feat(ci): enable gotest gha when push to main

- client/x/evmstaking/keeper/abci_test.go
- client/x/evmstaking/keeper/withdraw.go
- client/x/evmstaking/keeper/withdraw_test.go
Process residue reward after processing all completed unbondings. 
issue: none
> fix(evmstaking): process residue reward separately

- client/app/upgrades.go
- client/app/upgrades/polybius/constants.go
- client/app/upgrades/polybius/upgrades.go
Implement upgrade handler to increase `MaxValidators` to 80
issue: none
> feat(app): increase max validators

- client/x/evmstaking/keeper/abci_test.go
- client/x/evmstaking/keeper/keeper_test.go
- client/x/evmstaking/keeper/withdraw.go
- client/x/evmstaking/keeper/withdraw_test.go
- lib/netconf/chains.go
- lib/netconf/upgrades.go
In Story v1.2.1, the handling of residual rewards was upgraded. As a result, when syncing from the genesis block using a client running v1.2.1 or later, a state difference may occur at a certain block, leading to an app hash mismatch error. To address this issue, the residual reward handling logic has been corrected to properly account for the block height — applying the appropriate logic before and after the v1.2.1 upgrade point.
issue: none
> fix(evmstaking): handle residual reward by version

- client/app/rollback.go
Previously, the rollback command was only able to roll back a single latest block, regardless of the value provided via the `--number` flag. Even when attempting to roll back multiple blocks, the command would repeatedly revert to the state of `latest - 1` block without progressing further.
To enable proper multi-block rollback, the second parameter `removeBlock` in CometBFT’s `RollbackState` must be set to true. This allows the rollback loop to proceed block by block until the desired number of blocks is reverted. This PR updates the logic accordingly by setting removeBlock to true to support multi-block rollback as expected.
issue: none
> feat(cmd): enable to rollback multiple blocks

- client/proto/story/evmengine/v1/types/tx.proto
- client/x/evmengine/keeper/abci.go
- client/x/evmengine/keeper/abci_internal_test.go
- client/x/evmengine/keeper/keeper.go
- client/x/evmengine/keeper/keeper_internal_test.go
- client/x/evmengine/keeper/msg_server.go
- client/x/evmengine/keeper/msg_server_internal_test.go
- client/x/evmengine/types/convert.go
- client/x/evmengine/types/convert_test.go
- client/x/evmengine/types/customproto.go
- client/x/evmengine/types/customproto_test.go
- client/x/evmengine/types/tx.pb.go
- lib/promutil/evmengine.go
This changes to use protobuf encoding for payload. Ported from https://github.com/omni-network/omni/pull/2826.
issue: #527
> feat(evmengine): use protobuf to encode payload

- client/app/upgrades/polybius/constants.go
set the upgrade height of Polybius for Story mainnet. The block height is [8270000](https://www.storyscan.io/block/countdown/8270000) and the estimated time is about 00:30 UTC on September 5, 2025.
issue: none
> chore(upgrade): set polybius height for mainnet

- client/app/app.go
populate the version field on the abci-info endpoint
issue: #497
> fix(cli): report version on abci info endpoint

- client/app/app.go
- client/server/README.md
- client/server/payload.go
- client/server/staking.go
Added APIs to fetch the staked token amount.
Also, implemented `CreateQueryContext` to allow querying data at a specific block height via the `X-Block-Height` request header.
issue: #589
> feat(api): add endpoint to query staked token amount
