lib/netconf/local/genesis.json

adds additional ip allocations to local genesis network to make testing easier
issue: none

chore(client): update local genesis with new ip allocations

---

client/cmd/flags.go
client/cmd/key_utils.go
client/cmd/transaction.go
client/cmd/validator.go

updates the validator CLI with more validator operation support and more intuitive inputs
issue: resolves #57

feat(client): improves validator cli operations

---

client/x/evmstaking/keeper/abci.go

fix(log): remove delegation logs

---

client/app/abci.go
client/x/evmengine/keeper/abci.go

make key abci call log info so we can turn the debug level to info
issue: none

refactor(log): make abci log info

---

client/x/evmstaking/types/staking_contract_test.go

Increased test coverage of [client/x/evmstaking/types/staking_contract.go](https://github.com/piplabs/story/blob/main/client/x/evmstaking/types/staking_contract.go) from 0% to 100%.
issue: https://github.com/piplabs/story/issues/64

test(evmstaking/types): add test cases for staking contract

---

client/x/evmstaking/keeper/utils_test.go

Add test code for `utils.go`. 
issue: #64

test(evmstaking/keeper): add test cases for utils

---

client/x/evmengine/types/tx_test.go

increased coverage to 100%
issue: #81

test(evmengine/types): add test cases for tx

---

client/cmd/cmd.go
client/cmd/flags.go
client/cmd/status.go
client/cmd/validator.go

adds validator CLI subcommand for returning block height
issue: fixes #107

feat(cli): adds status cmd to fetch block height

---

lib/buildinfo/buildinfo.go

finalizes the stable release for `story` client version 0.10.0
issue: none

chore(release): finalize client 0.10.0 stable release

---

client/x/evmstaking/types/genesis_test.go

increase coverage to 100%
issue: #64

test(evmstaking): add test cases for genesis

---

client/x/evmengine/keeper/db_internal_test.go

increase coverage to 87.5%
**not covered**
- sdk collection related errors
issue: #81

test(evmengine): add test cases for db

---

client/x/evmengine/types/genesis_test.go

increased coverage to 100%
issue: #81

test(evmengine): add test cases for genesis

---

client/x/evmengine/types/params_test.go

increased coverage to 100%
issue: #81

test(evmengine): add test cases for params

---

client/app/upgrades.go
client/app/upgrades/v0_11_0/constants.go
client/app/upgrades/v0_11_0/upgrades.go
client/genutil/evm/predeploys/predeploys.go
client/x/evmengine/keeper/evmmsgs.go
lib/buildinfo/buildinfo.go

Hard fork upgrade to point CL to the fixed slashing contract https://github.com/piplabs/story/pull/146
issue: #80

fix(contracts): add v0.11.0 upgrade 

---

client/app/start.go
client/cmd/cmd.go
client/cmd/flags.go
client/config/config.go

add one block rollback cmd (ref. [cosmos-sdk](https://github.com/cosmos/cosmos-sdk/blob/6a0358607411cd83d22c6f1deea69f399f803007/server/rollback.go#L13-L14))
issue: #144

feat(cmd): one block rollback 

---

client/x/evmengine/keeper/abci_internal_test.go

increased coverage to 83.8%
added mock getPayloadV3Func to `mockEngineAPI` for mocking getPayloadV3
issue: #81

test(evmengine): add test cases for abci

---

lib/netconf/local/genesis.json

update the mint module genesis config of local network
issue: none

fix(netconf): fix genesis config of mint module in local netconf

---

lib/buildinfo/buildinfo.go

finalizes the v0.12.0 story consensus client stable release version
issue: none

chore(release): finalize client v0.12.0 stable release

---

client/x/evmengine/keeper/abci_internal_test.go
client/x/evmstaking/keeper/keeper_test.go
go.mod
go.sum

use the new release cosmos sdk with deterministic period delegation fix
issue: none

fix(evmstaking): use deterministic cosmos sdk

---

client/x/evmengine/keeper/abci.go
client/x/evmengine/keeper/abci_internal_test.go
client/x/evmengine/keeper/keeper.go
client/x/evmengine/keeper/keeper_internal_test.go
client/x/evmengine/keeper/upgrades.go
client/x/evmengine/types/tx.go
client/x/evmengine/types/tx_test.go
client/x/evmstaking/keeper/keeper.go
lib/cast/cast.go
lib/cast/cast_test.go
lib/ethclient/enginemock.go
lib/k1util/k1util.go

patches up security fixes found in omni's latest spearbit audit
issue: none

chore(security): port omni security fixes

---

contracts/script/GenerateAlloc.s.sol

add devnet settings for genesis file generation.
issue: #217

test(contracts): add devnet settings

---

lib/netconf/local/genesis.json
lib/netconf/odyssey/genesis.json

add `singularity_height` of mint module in odyssey network
issue: none

feat(mint): add singularity param for mint module

---

go.mod
go.sum

align with the cosmos sdk changes to fix rewards issue
issue: none

fix(rewards): align with cosmos sdk update

---

go.mod
go.sum

Bump cosmos-sdk version
issue: none

chore(version): bump cosmos sdk version

---

contracts/script/GenerateAlloc.s.sol

add odyssey testnet setting
issue: #217

feat(contracts): add odyssey testnet configs

---

contracts/Makefile
contracts/script/GenerateAlloc.s.sol

* add a convenient Makefile command to generate genesis file
* support mainnet chain id: 1514 in the script
issue: none

feat(script): add mainnet support

---

lib/netconf/local/genesis.json
lib/netconf/odyssey/genesis.json

Skip checking the delegation amount is greater than minimum self delegation at genesis block. 
issue: none

feat(genesis): skip validation of minimum self delegation

---

contracts/script/GenerateAlloc.s.sol

Allocate 1 wei balance to the precompiled contracts:
0x0100: p256Verify
0x0101: ipgraph
issue: none

chore(genesis): allocate balance to ipgraph precompiled contracts

---

client/x/evmengine/keeper/abci.go
client/x/evmengine/keeper/abci_internal_test.go
client/x/evmengine/keeper/msg_server.go
client/x/evmengine/keeper/msg_server_internal_test.go
client/x/evmengine/keeper/proposal_server.go
client/x/evmengine/keeper/proposal_server_internal_test.go
client/x/evmengine/testutil/expected_keepers_mocks.go
client/x/evmengine/types/expected_keepers.go
client/x/evmstaking/keeper/abci.go
client/x/evmstaking/keeper/genesis.go
client/x/evmstaking/keeper/keeper.go
client/x/evmstaking/keeper/reward_queue.go
client/x/evmstaking/keeper/withdraw.go
client/x/evmstaking/keeper/withdrawal_queue.go
client/x/evmstaking/keeper/withdrawal_queue_test.go
client/x/evmstaking/types/keys.go
lib/promutil/evmstaking.go

separate withdrawal and reward queue, which withdrawal queue has higher priority
issue: none

feat(evmstaking): separate withdrawal and reward queue

---

client/server/staking.go

fix(evmstaking): fix codec

---

lib/netconf/odyssey/genesis.json

updates max validators to 112
issue: none

chore(lib/netconf): update max validators to 112

---

contracts/foundry.toml
contracts/package.json
contracts/pnpm-lock.yaml
contracts/script/GenerateAlloc.s.sol
contracts/src/libraries/Predeploys.sol
contracts/test/erc6551/Erc6551Registry.t.sol
contracts/test/utils/Test.sol

feat(genesis): predeploy erc6551 registry

---

lib/buildinfo/buildinfo.go

finalize the story v0.12.1 stable release
issue: none

chore(release): finalize story v0.12.1 stable release

---

contracts/script/GenerateAlloc.s.sol
contracts/src/libraries/Predeploys.sol
contracts/test/upgrades/PredeployUpgrades.t.sol
contracts/test/utils/Test.sol

Proxies will be initialized to a deterministic but dead address. They can be upgraded later, or renounce upgradeability.
ProxyAdmins will be owned by the timelock.
issue: none

feat(genesis): reserve address space for 1024 proxies

---

lib/netconf/odyssey/genesis.json

update execution hash
issue: none

fix(lib): update execution hash

---

contracts/src/token/WIP.sol
contracts/test/token/WIP.t.sol

prevent send wip to zero address or wip contract as well self approval.
issue: resolves #283

chore(wip): prevent transfer to zero or wip

---

contracts/src/token/WIP.sol

restrict function mutability of symbol and name to pure
issue: none

fix(wip): restrict name and symbol to pure

---

contracts/script/GenerateAlloc.s.sol

correct canceller address setting
issue: #289

fix(contracts): correct canceller address

---

client/cmd/cometconfig.go

Increase the default timeout commit
issue: none

feat(config): increase timeout commit

---

client/app/abci.go

Added a log for calling finalize block to cometBFT.
issue: none

chore(app): add log for calling finalize block

---

lib/netconf/odyssey/genesis.json

add geth genesis file with 1k proxies and correct canceller
issue: none

feat(contracts): add geth genesis file

---

lib/buildinfo/buildinfo.go

finalizes preparation for the public 0.12.0 odyssey release version (due to a small hiccup the last minor bump was reverted)
issue: none

chore(release): finalize official odyssey release version

---

lib/netconf/odyssey/genesis.json

update the gen file
issue: none

chore(gen): update gen file

---

lib/buildinfo/buildinfo.go

introduces v0.12.1 story unstable release 
issue: none

chore(release): begin story v0.12.1 unstable release

---

client/app/upgrades.go
client/app/upgrades/v0_12_1/constants.go
client/app/upgrades/v0_12_1/upgrades.go

add and begin v0.12.1 upgrade
issue: #307

feat(upgrades): add v0.12.1 upgrade

---

client/app/upgrades/v0_12_1/upgrades.go

fix logs in v0.12.1 upgrade
issue: none

fix(upgrades): fix upgrade log

---

client/x/evmstaking/keeper/withdraw.go

With multiple delegations from a delegator, the claimed reward was withdrawn multiple. Fix the issue by processing eligible reward withdrawal.
issue: #319

fix(evmstaking): fix double spent issue of claimed reward

---

client/x/evmstaking/keeper/deposit.go
client/x/evmstaking/keeper/validator.go

fix overwrite issue of withdraw and reward address
issue: none

fix(evmstaking): fix overwrite issue of withdraw and reward address

---

lib/buildinfo/buildinfo.go

begin story 0.12.2 unstable release
issue: none

chore(release): begin story 0.12.2 unstable release

---

client/server/cometbft.go
client/server/payload.go
client/server/server.go

chore(server): fix typo of comet bft

---

.pre-commit-config.yaml
client/server/README.md
client/server/api.swagger.yaml

add story api docs
issue: none

feat(doc): add api document

---

client/x/evmengine/keeper/ubi.go
client/x/evmengine/keeper/upgrades.go
client/x/evmengine/testutil/expected_keepers_mocks.go
client/x/evmstaking/keeper/delegator_address.go
client/x/evmstaking/keeper/deposit.go
client/x/evmstaking/keeper/keeper_test.go
client/x/evmstaking/keeper/redelegation.go
client/x/evmstaking/keeper/unjail.go
client/x/evmstaking/keeper/unjail_test.go
client/x/evmstaking/keeper/update_commission.go
client/x/evmstaking/keeper/validator.go
client/x/evmstaking/keeper/withdraw.go
client/x/evmstaking/testutil/expected_keepers_mocks.go

use `CachedContext` to prevent partial state on failure txn
issue: none

fix(evmstaking): prevent partial state on failure txn

---

client/x/evmstaking/keeper/keys.go

fix the issue on converting uncompressed pubkey to compressed pubkey
issue: fixes #347

fix(evmstaking): compress uncmp key to cmp key

---

lib/buildinfo/buildinfo.go

finalize story 0.13.0 stable release
issue: none

chore(release): finalize story 0.13.0 stable release

---

lib/buildinfo/buildinfo.go

Start the unstable version of 0.13.1
issue: none

chore(version): start 0.13.1 unstable

---

client/server/server.go

enhance api server security
issue: none

fix(api): enhance api server security

---

client/cmd/validator.go

compatible change on CLI for staking contract chargeFee change
issue: none

fix(cli): cli txn fee compatibility

---

lib/buildinfo/buildinfo.go

finalize story 0.13.1 stable release. **let's not merge it before merging #385** 
issue: none

chore(release): finalize story 0.13.1 stable release

---

lib/buildinfo/buildinfo.go

begin story 0.13.2 unstable release
issue: none

chore(release): begin story 0.13.2 unstable release

---

client/config/config.go

Enable optimistic build in Odyssey
issue: close #389

chore(*): enable optimistic build

---

client/app/prouter.go

Add the check to make sure the node receive the correct number of txs.
Tested in local testnet
issue: close #376

fix(prouter): add tx number check

---

client/x/evmstaking/keeper/keys.go

Lack Of Pubkey Integrity Checks
issue: none

fix(evmstaking): validate uncompressed pubkey on curve

---

client/x/evmengine/types/tx.go

[TRST-L1-R-1] Handling of empty log topics
issue: none

fix(events): add comments for event converting

---

client/app/start.go
client/cmd/flags.go
client/cmd/testdata/TestCLIReference_run.golden
client/cmd/testdata/TestRunCmd_defaults.golden
client/cmd/testdata/TestRunCmd_flags.golden
client/cmd/testdata/TestRunCmd_json_files.golden
client/cmd/testdata/TestRunCmd_toml_files.golden
client/config/config.go
client/config/config.toml.tmpl
client/config/testdata/default.toml
client/config/testdata/story.toml
client/server/config.go
client/server/server.go

[TRST-L1-M-6] Misconfigurations in HTTP server enables Slowloris and header overload attacks
issue: none

fix(api): make api server configurable

---

client/cmd/cometconfig.go
client/cmd/comettoml.go
client/cmd/init.go

port the config template from cometbft to enable the customization on cometbft mempool type
issue: none

fix(config): disable cometbft mempool

---

client/app/upgrades.go

set v0.14.0 upgrade handler to app
issue: none

chore(upgrade): set upgrade handler to app

---

lib/buildinfo/buildinfo.go

finalize story 0.14.0 stable release. It should be merged after @lucas2brh's testing.
issue: none

chore(release): finalize story 0.14.0 stable release

---

lib/buildinfo/buildinfo.go

begin story 0.14.1 unstable release
issue: none

chore(release): begin story 0.14.1 unstable release

---

contracts/script/GenerateAlloc.s.sol
contracts/script/utils/EIP1967Helper.sol
contracts/script/utils/InitializableHelper.sol
contracts/src/deploy/Create3.sol
contracts/src/interfaces/IIPTokenStaking.sol
contracts/src/interfaces/IUBIPool.sol
contracts/src/interfaces/IUpgradeEntrypoint.sol
contracts/src/libraries/Predeploys.sol
contracts/src/libraries/Secp256k1.sol
contracts/src/protocol/IPTokenStaking.sol
contracts/src/protocol/PubKeyVerifier.sol
contracts/src/protocol/UBIPool.sol
contracts/src/protocol/UpgradeEntrypoint.sol
contracts/src/token/WIP.sol
contracts/test/data/ValidatorData.sol
contracts/test/deploy/Create3.t.sol
contracts/test/erc6551/Erc6551Registry.t.sol
contracts/test/libraries/Secp256k1.t.sol
contracts/test/stake/IPTokenStaking.t.sol
contracts/test/timelock/Timelock.t.sol
contracts/test/token/WIP.t.sol
contracts/test/ubipool/UBIPool.t.sol
contracts/test/upgrade-entrypoint/UpgradeEntryPoint.t.sol
contracts/test/upgrades/PredeployUpgrades.t.sol
contracts/test/utils/Test.sol

Fix pragma version to 0.8.23
issue: none

fix(contracts): remove floating pragma

---

scripts/verifypr/verify.go

allow cross-repo issue reference (e.g. piplabs/story-geth#1) in the issue section
issue: none

fix(scripts): verifypr cross-ref repo issue

---

client/app/app.go

import local modules to register modules during depinject's `doInject` phase
issue: none

fix(app): import modules for side effects on proto

---

client/x/evmstaking/types/params.go

correct default value of evmstaking params
issue: none

fix(evmstaking): correct default value of evmstaking params

---

go.mod
go.sum

upgrade cosmos dep
issue: none

chore(staking): upgrade cosmos dep

---

contracts/package.json
contracts/pnpm-lock.yaml
contracts/src/protocol/PubKeyVerifier.sol
contracts/test/stake/IPTokenStaking.t.sol

checks that the argument (uncompressed) secp256k1 pubkey is on curve
issue: closes #375

feat(contracts): secp256k1 verify on curve

---

lib/netconf/story/genesis.json

Update execution hash corresponding to this change (https://github.com/piplabs/story-geth/pull/84)
issue: none

chore(*): update execution hash for story

---

client/cmd/cometconfig.go

Update story default config
issue: none

chore(*): update story config

---

lib/netconf/story/genesis.json

Official Validator 1 and 2 by Story Foundation
issue: none

chore(genesis): update mainnet validator in genesis

---

lib/netconf/story/genesis.json

Set genesis validators with addresses derived from EVM address. 
issue: none

feat(genesis): set genesis validators for mainnet

---

go.mod
go.sum
lib/buildinfo/buildinfo.go

rounding fix dep upgrade
issue: none

fix(distribution): rounding fix dep upgrade

---

lib/buildinfo/buildinfo.go

begin story 1.1.0 unstable release
issue: none

chore(release): begin story 1.1.0 unstable release

---

.github/CODEOWNERS

update code owners
issue: none

chore(*): update code owners

---

client/x/evmstaking/keeper/withdraw.go

remove redundant amount attr for unstake result log
issue: none

fix(evmstaking): remove redundant amount attr

---

client/server/README.md
client/server/payload.go
client/server/staking.go
go.mod
go.sum

period delegation api returns token amount
issue: none

feat(api): period delegation api returns token amount

---

.github/CODEOWNERS

separate devops and dev owners
issue: none

chore(*): update codeowner

---

lib/buildinfo/buildinfo.go

finalize story 1.1.0 stable release
issue: none

chore(release): finalize story 1.1.0 stable release

---

scripts/verifypr/verify.go

Allow longer pr title
issue: none

chore(*): allow longer pr title

---

lib/buildinfo/buildinfo.go

begin story 1.1.1 unstable release
issue: none

chore(release): begin story 1.1.1 unstable release

---

client/x/evmengine/README.md
client/x/evmstaking/README.md

add readme for `evmengine` and `evmstaking`
issue: none

docs(x/*): module readme

---

client/server/README.md

update story api doc to fit the previous change
issue: none

docs(api): update story api doc

---

contracts/src/protocol/IPTokenStaking.sol

Resolve some issues regarding comments of staking contract reported in Cantina.
- https://cantina.xyz/code/0561defa-eeb2-4a74-8884-5d7a873afa58/findings/376
- https://cantina.xyz/code/0561defa-eeb2-4a74-8884-5d7a873afa58/findings/379
- https://cantina.xyz/code/0561defa-eeb2-4a74-8884-5d7a873afa58/findings/381
issue: none

chore(contracts): update the comments in staking contract

---

client/cmd/flags.go
client/cmd/validator.go

Add a CLI to generate `priv_validator_key.json` file from EVM private key. 
issue: none

feat(cli): add cli to generate priv json file from evm key

---

.github/workflows/ci-docker-hub.yml

**CONTEXT**
The workflow to push images to ghcr has some hiccup. 
**PR NOTES**
1/ Update workflow title
2/ add input for workflow_dispatch trigger, handle the case if version is provisioned manually
3/ optimize docker caching strategy
issue: none

feat(ci): fix gha workflow to push docker images

---

.github/workflows/build-release-artifacts.yml

chore(ci): change workflow runner version
issue: none

chore(ci): change workflow runner version

---

lib/buildinfo/buildinfo.go

finalize story 1.1.1 stable release
issue: none

chore(release): finalize story 1.1.1 stable release

---

lib/buildinfo/buildinfo.go

begin story 1.1.2 unstable release
issue: none

chore(release): begin story 1.1.2 unstable release

---

client/cmd/flags.go

Added a verification of max commission change rate. It cannot be greater than max commission rate.
issue: #488

chore(cli): add verification of max comm change rate

---

client/server/utils/querymap.go

Fix incorrect conversion between integer types in API
issue: fixes #433

fix(api): incorrect type conversion

---

.github/workflows/notify-slack-on-pr-merge.yml

send notification to qa-messenger channel once a pr merged to the default branch
issue: none

feat(ci): add qa messenger notification once a pr merged

---

.github/workflows/main.yml

improve the main workflow to trigger downstream workflow
issue: none

feat(ci): add workflow trigger

---

.secrets.baseline
client/config/config.go

rename encrypted key file to `priv_validator_key.enc` per request from @vtiwari-story 
issue: none

chore(cli): rename encrypted key file

---

lib/buildinfo/buildinfo.go

finalize story 1.2.0 stable release
issue: none

chore(release): finalize story 1.2.0 stable release

---

lib/buildinfo/buildinfo.go

begin story 1.2.1 unstable release
issue: none

chore(release): begin story 1.2.1 unstable release

---

.codecov.yml
.github/workflows/ci-pr.yml
.github/workflows/gotest.yml
README.md

Add codecov github action. Require to set github secret `CODECOV_TOKEN`.
issue: none

feat(ci): add codecov gha

---

client/cmd/validator.go

Show EVM address signing the transaction
issue: #553

chore(cli): show evm addr signing transaction

---

client/cmd/flags.go
lib/cmd/cmd.go

After [this change](https://github.com/piplabs/story/commit/9771a9adec4b0b56c081cf52ed9c1da33614f1dd#diff-90a411c64bb0f3261c58947a215ef9736429a1ac026ba6424528b3abad3a9ea5), the configurations of log and state sync has not been loaded correctly from `story.toml`. This PR is to fix the issue by handling them to load correctly. 
issue: #547

fix(cmd): fix to load log and state sync config correctly from toml

---

client/x/mint/keeper/abci_test.go
client/x/mint/keeper/genesis_test.go
client/x/mint/keeper/grpc_query_test.go
client/x/mint/keeper/keeper_test.go
client/x/mint/keeper/params_test.go
client/x/mint/types/genesis_test.go
client/x/mint/types/params_test.go

Added unit tests for mint module. 
issue: none

test(mint): add unit tests for mint module

---

lib/buildinfo/buildinfo.go

finalize story 1.2.1 stable release
issue: none

chore(release): finalize story 1.2.1 stable release

---

client/server/README.md
client/server/staking.go

Add to query the total number of rewards token of delegator. This is to estimate the daily rewards for staking dashboard.
issue: none

feat(api): query delegator total rewards token

---

client/server/README.md
client/server/payload.go
client/server/staking.go

add query to get delegator's rewards tokens
issue: none

feat(api): add query to get delegator rewards token

---

lib/buildinfo/buildinfo.go

finalize story 1.3.2 stable release
issue: none

chore(release): finalize story 1.3.2 stable release
